// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BackgroundOfSmallImagesDocumentDataSlicesSlice = SmallBackgroundImageSlice;

/**
 * Content for Background Of Small Images documents
 */
interface BackgroundOfSmallImagesDocumentData {
  /**
   * Slice Zone field in *Background Of Small Images*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: background_of_small_images.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BackgroundOfSmallImagesDocumentDataSlicesSlice>;
}

/**
 * Background Of Small Images document from Prismic
 *
 * - **API ID**: `background_of_small_images`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BackgroundOfSmallImagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BackgroundOfSmallImagesDocumentData>,
    "background_of_small_images",
    Lang
  >;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Background Image field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Terms and Conditions Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.terms_and_conditions_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  terms_and_conditions_text: prismic.RichTextField;

  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Company Name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Privacy Policy Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.privacy_policy_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_policy_link: prismic.LinkField;

  /**
   * Terms and Conditions Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.terms_and_conditions_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  terms_and_conditions_link: prismic.LinkField;

  /**
   * Whatsapp Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.whatsapp_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  whatsapp_link: prismic.LinkField;

  /**
   * Whatsapp Icon Color field in *Footer*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.whatsapp_icon_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  whatsapp_icon_color: prismic.ColorField;

  /**
   * Whatsapp Icon Background Color field in *Footer*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.whatsapp_icon_background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  whatsapp_icon_background_color: prismic.ColorField;

  /**
   * Medical Marketing Website Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.medical_marketing_website_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  medical_marketing_website_link: prismic.LinkField;

  /**
   * Medical Marketing Website Link Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.medical_marketing_website_link_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  medical_marketing_website_link_text: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Background Color field in *Header*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: header.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * CTA Icon field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cta_icon: prismic.ImageField<never>;

  /**
   * CTA Message field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_message: prismic.KeyTextField;

  /**
   * CTA Phone field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_phone: prismic.KeyTextField;

  /**
   * CTA Link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * CTA Text Color field in *Header*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_text_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cta_text_color: prismic.ColorField;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

/**
 * Content for iFrame documents
 */
interface IframeDocumentData {
  /**
   * CTA iFrame field in *iFrame*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iframe.cta_iframe
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_iframe: prismic.KeyTextField;
}

/**
 * iFrame document from Prismic
 *
 * - **API ID**: `iframe`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IframeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<IframeDocumentData>, "iframe", Lang>;

type LandingPageDocumentDataSlicesSlice =
  | ComparisonSlice
  | Section2Slice
  | Section3Slice
  | Section1Slice
  | ReviewsSlice
  | HeroSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Primary Color field in *Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.primary_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  primary_color: prismic.ColorField;

  /**
   * Secondary Color field in *Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.secondary_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  secondary_color: prismic.ColorField;

  /**
   * CTA Text Color field in *Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_text_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cta_text_color: prismic.ColorField;

  /**
   * CTA Background Color field in *Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cta_background_color: prismic.ColorField;

  /**
   * Favicon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * GTM_ID field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.gtm_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gtm_id: prismic.KeyTextField;

  /**
   * default iFrame field in *Settings*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.default_iframe
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  default_iframe: prismic.ContentRelationshipField<"iframe">;

  /**
   * Block Indexing by Search Engines field in *Settings*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: settings.block_indexing_by_search_engines
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  block_indexing_by_search_engines: prismic.BooleanField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BackgroundOfSmallImagesDocument
  | FooterDocument
  | HeaderDocument
  | IframeDocument
  | LandingPageDocument
  | SettingsDocument;

/**
 * Primary content in *Comparison → Primary*
 */
export interface ComparisonSliceDefaultPrimary {
  /**
   * Title field in *Comparison → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Title Color field in *Comparison → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * CTA Text field in *Comparison → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * iFrame field in *Comparison → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.iframe
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  iframe: prismic.ContentRelationshipField<"iframe">;

  /**
   * CTA Link field in *Comparison → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * After CTA Text field in *Comparison → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.after_cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta_text: prismic.RichTextField;

  /**
   * Text Color field in *Comparison → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * Background Image field in *Comparison → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Of Small Images field in *Comparison → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.primary.background_of_small_images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_of_small_images: prismic.ContentRelationshipField<"background_of_small_images">;
}

/**
 * Primary content in *Comparison → Items*
 */
export interface ComparisonSliceDefaultItem {
  /**
   * Image 1 field in *Comparison → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.items[].image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Comparison → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison.items[].image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;
}

/**
 * Default variation for Comparison Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComparisonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComparisonSliceDefaultPrimary>,
  Simplify<ComparisonSliceDefaultItem>
>;

/**
 * Slice variation for *Comparison*
 */
type ComparisonSliceVariation = ComparisonSliceDefault;

/**
 * Comparison Shared Slice
 *
 * - **API ID**: `comparison`
 * - **Description**: Comparison
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComparisonSlice = prismic.SharedSlice<
  "comparison",
  ComparisonSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Bond field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.bond
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bond: prismic.RichTextField;

  /**
   * Bond Color field in *Hero → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.bond_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  bond_color: prismic.ColorField;

  /**
   * Header field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;

  /**
   * Header Color field in *Hero → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.header_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  header_color: prismic.ColorField;

  /**
   * Sub Header field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.sub_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_header: prismic.RichTextField;

  /**
   * Sub Header Color field in *Hero → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.sub_header_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  sub_header_color: prismic.ColorField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Popup Video field in *Hero → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.popup_video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  popup_video: prismic.EmbedField;

  /**
   * CTA Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * iFrame field in *Hero → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.iframe
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  iframe: prismic.ContentRelationshipField<"iframe">;

  /**
   * CTA Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * After CTA Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.after_cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta_text: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Image For Mobile Devices field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image_for_mobile_devices
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image_for_mobile_devices: prismic.ImageField<never>;

  /**
   * Transition Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.transition_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  transition_image: prismic.ImageField<never>;

  /**
   * Background Of Small Images field in *Hero → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_of_small_images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_of_small_images: prismic.ContentRelationshipField<"background_of_small_images">;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Key Point Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].key_point_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  key_point_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Reviews → Primary*
 */
export interface ReviewsSliceDefaultPrimary {
  /**
   * Title field in *Reviews → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Title Color field in *Reviews → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * Image field in *Reviews → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Image field in *Reviews → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Testimonial Color field in *Reviews → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.primary.testimonial_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  testimonial_color: prismic.ColorField;

  /**
   * Background Of Small Images field in *Reviews → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.primary.background_of_small_images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_of_small_images: prismic.ContentRelationshipField<"background_of_small_images">;
}

/**
 * Primary content in *Reviews → Items*
 */
export interface ReviewsSliceDefaultItem {
  /**
   * Testimonial field in *Reviews → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial: prismic.RichTextField;

  /**
   * Name field in *Reviews → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSliceDefaultPrimary>,
  Simplify<ReviewsSliceDefaultItem>
>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault;

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSlice = prismic.SharedSlice<
  "reviews",
  ReviewsSliceVariation
>;

/**
 * Primary content in *Section1 → Primary*
 */
export interface Section1SliceDefaultPrimary {
  /**
   * Title field in *Section1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Title Color field in *Section1 → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * Image field in *Section1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *Section1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Text Color field in *Section1 → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * CTA Text field in *Section1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * iFrame field in *Section1 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.iframe
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  iframe: prismic.ContentRelationshipField<"iframe">;

  /**
   * CTA Link field in *Section1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * After CTA Text field in *Section1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.after_cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta_text: prismic.RichTextField;

  /**
   * Background Image field in *Section1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Transition In Image field in *Section1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.transition_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  transition_image_1: prismic.ImageField<never>;

  /**
   * Transition Out Image field in *Section1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.transition_out_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  transition_out_image: prismic.ImageField<never>;

  /**
   * Background Of Small Images field in *Section1 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section1.primary.background_of_small_images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_of_small_images: prismic.ContentRelationshipField<"background_of_small_images">;
}

/**
 * Default variation for Section1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Section1SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section1*
 */
type Section1SliceVariation = Section1SliceDefault;

/**
 * Section1 Shared Slice
 *
 * - **API ID**: `section1`
 * - **Description**: Section1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section1Slice = prismic.SharedSlice<
  "section1",
  Section1SliceVariation
>;

/**
 * Primary content in *Section2 → Primary*
 */
export interface Section2SliceDefaultPrimary {
  /**
   * Title field in *Section2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Title Color field in *Section2 → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * CTA Text field in *Section2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * iFrame field in *Section2 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.iframe
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  iframe: prismic.ContentRelationshipField<"iframe">;

  /**
   * CTA Link field in *Section2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * After CTA Text field in *Section2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.after_cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta_text: prismic.RichTextField;

  /**
   * Background Image field in *Section2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Transition In Image field in *Section2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.transition_in_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  transition_in_image: prismic.ImageField<never>;

  /**
   * Transition Out Image field in *Section2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.transition_out_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  transition_out_image: prismic.ImageField<never>;

  /**
   * Key Point Icon field in *Section2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.key_point_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  key_point_icon: prismic.ImageField<never>;

  /**
   * Key Points Text Color field in *Section2 → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * Background Of Small Images field in *Section2 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.background_of_small_images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_of_small_images: prismic.ContentRelationshipField<"background_of_small_images">;
}

/**
 * Primary content in *Section2 → Items*
 */
export interface Section2SliceDefaultItem {
  /**
   * heading field in *Section2 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * description field in *Section2 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Section2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Section2SliceDefaultPrimary>,
  Simplify<Section2SliceDefaultItem>
>;

/**
 * Primary content in *Section2 → Primary*
 */
export interface Section2SlicePointBlocksPrimary {
  /**
   * Title field in *Section2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Title Color field in *Section2 → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * CTA Text field in *Section2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * iFrame field in *Section2 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.iframe
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  iframe: prismic.ContentRelationshipField<"iframe">;

  /**
   * CTA Link field in *Section2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * After CTA Text field in *Section2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.after_cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta_text: prismic.RichTextField;

  /**
   * Background Image field in *Section2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Transition In Image field in *Section2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.transition_in_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  transition_in_image: prismic.ImageField<never>;

  /**
   * Transition Out Image field in *Section2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.transition_out_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  transition_out_image: prismic.ImageField<never>;

  /**
   * Key Points Text Color field in *Section2 → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * Index Number Background Color field in *Section2 → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.index_number_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  index_number_background_color: prismic.ColorField;

  /**
   * Key Point Background Color field in *Section2 → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.key_point_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  key_point_background_color: prismic.ColorField;

  /**
   * Background Of Small Images field in *Section2 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.primary.background_of_small_images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_of_small_images: prismic.ContentRelationshipField<"background_of_small_images">;
}

/**
 * Primary content in *Section2 → Items*
 */
export interface Section2SlicePointBlocksItem {
  /**
   * heading field in *Section2 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * description field in *Section2 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * PointBlocks variation for Section2 Slice
 *
 * - **API ID**: `pointBlocks`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section2SlicePointBlocks = prismic.SharedSliceVariation<
  "pointBlocks",
  Simplify<Section2SlicePointBlocksPrimary>,
  Simplify<Section2SlicePointBlocksItem>
>;

/**
 * Slice variation for *Section2*
 */
type Section2SliceVariation = Section2SliceDefault | Section2SlicePointBlocks;

/**
 * Section2 Shared Slice
 *
 * - **API ID**: `section2`
 * - **Description**: Section2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section2Slice = prismic.SharedSlice<
  "section2",
  Section2SliceVariation
>;

/**
 * Primary content in *Section3 → Items*
 */
export interface Section3SliceDefaultItem {
  /**
   * Title field in *Section3 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Title Color field in *Section3 → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * Paragraph field in *Section3 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Paragraph Color field in *Section3 → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].paragraph_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  paragraph_color: prismic.ColorField;

  /**
   * CTA Text field in *Section3 → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * iFrame field in *Section3 → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].iframe
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  iframe: prismic.ContentRelationshipField<"iframe">;

  /**
   * CTA Link field in *Section3 → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * After CTA Text field in *Section3 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].after_cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta_text: prismic.RichTextField;

  /**
   * Image field in *Section3 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video Embed iFrame field in *Section3 → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].video_embed_iframe
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_embed_iframe: prismic.KeyTextField;

  /**
   * Keep Image Right field in *Section3 → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: section3.items[].keep_image_right
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  keep_image_right: prismic.BooleanField;

  /**
   * Image below Text on Mobile field in *Section3 → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: section3.items[].image_below_text_on_mobile
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_below_text_on_mobile: prismic.BooleanField;

  /**
   * Background Image field in *Section3 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Of Small Images field in *Section3 → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section3.items[].background_of_small_images
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_of_small_images: prismic.ContentRelationshipField<"background_of_small_images">;
}

/**
 * Default variation for Section3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section3SliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<Section3SliceDefaultItem>
>;

/**
 * Slice variation for *Section3*
 */
type Section3SliceVariation = Section3SliceDefault;

/**
 * Section3 Shared Slice
 *
 * - **API ID**: `section3`
 * - **Description**: Section3
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section3Slice = prismic.SharedSlice<
  "section3",
  Section3SliceVariation
>;

/**
 * Primary content in *SmallBackgroundImage → Primary*
 */
export interface SmallBackgroundImageSliceDefaultPrimary {
  /**
   * Small Background Image field in *SmallBackgroundImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_background_image.primary.small_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  small_background_image: prismic.ImageField<never>;

  /**
   * Top field in *SmallBackgroundImage → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: small_background_image.primary.top
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  top: prismic.NumberField;

  /**
   * Right field in *SmallBackgroundImage → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: small_background_image.primary.right
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  right: prismic.NumberField;

  /**
   * Bottom field in *SmallBackgroundImage → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: small_background_image.primary.bottom
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  bottom: prismic.NumberField;

  /**
   * Left field in *SmallBackgroundImage → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: small_background_image.primary.left
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  left: prismic.NumberField;
}

/**
 * Default variation for SmallBackgroundImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallBackgroundImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmallBackgroundImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SmallBackgroundImage*
 */
type SmallBackgroundImageSliceVariation = SmallBackgroundImageSliceDefault;

/**
 * SmallBackgroundImage Shared Slice
 *
 * - **API ID**: `small_background_image`
 * - **Description**: SmallBackgroundImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallBackgroundImageSlice = prismic.SharedSlice<
  "small_background_image",
  SmallBackgroundImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BackgroundOfSmallImagesDocument,
      BackgroundOfSmallImagesDocumentData,
      BackgroundOfSmallImagesDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      IframeDocument,
      IframeDocumentData,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      ComparisonSlice,
      ComparisonSliceDefaultPrimary,
      ComparisonSliceDefaultItem,
      ComparisonSliceVariation,
      ComparisonSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      ReviewsSlice,
      ReviewsSliceDefaultPrimary,
      ReviewsSliceDefaultItem,
      ReviewsSliceVariation,
      ReviewsSliceDefault,
      Section1Slice,
      Section1SliceDefaultPrimary,
      Section1SliceVariation,
      Section1SliceDefault,
      Section2Slice,
      Section2SliceDefaultPrimary,
      Section2SliceDefaultItem,
      Section2SlicePointBlocksPrimary,
      Section2SlicePointBlocksItem,
      Section2SliceVariation,
      Section2SliceDefault,
      Section2SlicePointBlocks,
      Section3Slice,
      Section3SliceDefaultItem,
      Section3SliceVariation,
      Section3SliceDefault,
      SmallBackgroundImageSlice,
      SmallBackgroundImageSliceDefaultPrimary,
      SmallBackgroundImageSliceVariation,
      SmallBackgroundImageSliceDefault,
    };
  }
}
