// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  comparison: dynamic(() => import("./Comparison")),
  hero: dynamic(() => import("./Hero")),
  reviews: dynamic(() => import("./Reviews")),
  section1: dynamic(() => import("./Section1")),
  section2: dynamic(() => import("./Section2")),
  section3: dynamic(() => import("./Section3")),
  small_background_image: dynamic(() => import("./SmallBackgroundImage")),
};
